### ISSUE TITLE
UA-DETRAC dataset

### ISSUE THREAD

**Issue by edwardnguyen1705** [Omunkhuush/UA_DETRAC-preprocess#1]
Dear @Omunkhuush ,

Thanks for sharing your work.

The dataset download link is dead, could you share me the dataset on GoogleDrive?

Thanks so much for your time.

**Comment by Omunkhuush** [comment]
Hi,
Could you download from Kaggle?
https://www.kaggle.com/datasets/dtrnngc/ua-detrac-dataset

**Comment by edwardnguyen1705** [comment]
> Hi, Could you download from Kaggle? https://www.kaggle.com/datasets/dtrnngc/ua-detrac-dataset

Thank you!
